### PR TITLE
Update sensor.py

### LINKED ISSUE #99: Avoid that unavailable and unknown values are used to make average.
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**
  I use the average sensor to calculate average temperature in the house. I am using 6 zigbee sensor. If the battery of one gets 
 low it disconnects and it reports unavailable or unknown as state. I can notice this as the average value drops because i think 
 that the value is used to make the average is 0.

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**
 Just make one sensor states to report "unavailable" or "unknown"

**Expected behavior**

  Ignore "unavailable" and "unknown" states of the sensors

**Debug log**

```text

Add your logs here.

```

**Additional context**

### PR DESCRIPTION
**Pull request by mtb-xt**
Hopefully fixes https://github.com/Limych/ha-average/issues/99

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml

```

## Additional information

- This PR fixes or closes issue: fixes #99
- This PR is related to issue:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

### CODE REVIEW

**Comment by maia** [comment]
@mtb-xt Does your pull request fix the issue? If yes, any ideas why it's not part of the recent releases? Thanks!

**Comment by mtb-xt** [comment]
> @mtb-xt Does your pull request fix the issue? If yes, any ideas why it's not part of the recent releases? Thanks!

Yes, it fixes this issue for my home systems. Unfortunately, Limych seems to have abandoned the project, that's why the fork and the tag.

**Comment by maia** [comment]
> Yes, it fixes this issue for my home systems. Unfortunately, Limych seems to have abandoned the project, that's why the fork and the tag.

Thanks. Can you suggest an easy way to use your version? Shall I manually edit the files in my HA installation or is there a more convenient way? @Limych did update the project in the past months, he unfortunately just chose to ignore your pull request.

**Comment by mtb-xt** [comment]
> > Yes, it fixes this issue for my home systems. Unfortunately, Limych seems to have abandoned the project, that's why the fork and the tag.
> 
> Thanks. Can you suggest an easy way to use your version? Shall I manually edit the files in my HA installation or is there a more convenient way? @Limych did update the project in the past months, he unfortunately just chose to ignore your pull request.

If you're using HACS, then you can add this github repo as a custom repository and just install as usual.
image
image

**Comment by maia** [comment]
Thanks, but isn't your fork way behind in many other aspects? I'm wondering how to use the most recent version of ha-average but *with* your fix. I'm a complete novice with `git`, but I assume it needs a `git rebase` or `git merge`?

Bildschirmfoto 2024-03-27 um 10 36 03

**Pull request merged**
